/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room3.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_51002.geometry} material={materials.color2} />
        <mesh geometry={nodes.Mesh_51002_1.geometry} material={materials.color3} />
      </group>
    </group>
  )
}

useGLTF.preload('/room3.glb')
