/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room8.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_307002.geometry} material={materials['color.067']} />
        <mesh geometry={nodes.Mesh_307002_1.geometry} material={materials['color.069']} />
      </group>
    </group>
  )
}

useGLTF.preload('/room8.glb')
