/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room4.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_130002.geometry} material={materials['color.017']} />
        <mesh geometry={nodes.Mesh_130002_1.geometry} material={materials['color.019']} />
      </group>
    </group>
  )
}

useGLTF.preload('/room4.glb')
