/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Mesh_0002_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh_0002_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/room2.glb')
