/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.53, 0.01, 0.03]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_167002.geometry} material={materials['color.037']} />
        <mesh geometry={nodes.Mesh_167002_1.geometry} material={materials['color.039']} />
        <mesh geometry={nodes.door001.geometry} material={materials['color.040']} position={[0.51, 1.12, 1.76]} />
      </group>
    </group>
  )
}

useGLTF.preload('/room5.glb')
